### ISSUE TITLE
必要な機能まとめる

### ISSUE THREAD

**Issue by fumihumi** [ISC-MakeIT/f_college_sns#10]
トップページ（未定） 既存ページを使うかLP的なものにするか。
---------------------

 各作品を一覧で閲覧できるページ
-------------------

 - [ミスコン, mercariみたいな](https://misscolle.com/) カード形式
 - もしくは [グノシーみたいな](https://gunosy.com/categories/1)リストぽくするか

### 載せたい情報
 - ラフスケッチ画像
 - モデルのコンセプト
 - 応援されている数、PV数

 それぞれの作品を閲覧できる詳細ページ
-------------

 - 一覧ページだけで表せない情報載せる

- ラフスケッチ画像、そのほか製作中の画像などあればそれをカルーセルで表示するとか。
- 作品コンセプト
- 作品概要
- アピールポイント？
- 制作メンバーの名前
- 制作メンバーからの一言？（アピールと同じになりそうな）

- 機能面的な

```
- 閲覧者はこの作品に応援(いいね機能)ができる
（コメント機能も検討はしている）

- またリアルタイム( ≒ リアルタイム)でPV数を測ってそれっぽく出す？

```

 最初から最後までのもでるに対して投票するページ
-------------------
 - モデルのラフスケッチを大きく表示。
その下に投票ボタンを用意する
（かっこいい、かわいい、優しそう、綺麗、きて見たい）...etc
→この中から一つ選んでもらう

  - １人目に対して投稿したら次へボタンがおせる
  - ２人目以降は `前へ`, `次へ` がおせる

  - 基本的に一人１投票なので再投票などは一旦検討しない。

**Comment by ymzk-jp** [comment]
ミスコンのサイトは俯瞰できるのでわかりやすいと思う

**Comment by ymzk-jp** [comment]
投票システムがちょっと分かりづらいし煩雑な気がするのでちょっと改めたいと思ったりらじばんだり

**Comment by fumihumi** [comment]
投票に関しては↑の内容を先日にお伝えはしたので先方次第なのかなと思ってますー

**Comment by fumihumi** [comment]
それ(↑のアイデア)が採用されるのかもしくはもともと検討していた一人一票なのか。

**Comment by fumihumi** [comment]
そういえば投票
#24 

やっぱり当初の仕組みになるかーーーーうーん
