### ISSUE TITLE
よい投票システムを考える

### ISSUE THREAD

**Issue by ymzk-jp** [ISC-MakeIT/f_college_sns#15]
## 概要
よい投票システムを検討し具体的な要件定義を作成する

**Comment by ymzk-jp** [comment]
#####  [事前情報](https://github.com/ISC-MakeIT/f_college_sns/issues/24)

以下重要部分抜粋
```text
. 開演前、休憩に入る前、投票タイムはスクリーンにスマホリンク用QRからの誘導
. 来場者は学生だけではない
. コンテスト中のプロジェクターの利用は、テクニカルから基本考えないでほしいと言われています→審査員のみなさんが審査に集中したいのと、観客のみなさんにもステージに集中させたいため
. スクリーン上QR + メッセージ + 司会からのアナウンス→ 投票スタート→ 投票締切→ 集計→投票結果がプロジェクター投影→ 司会オーディエンス賞発表→ 休憩
「ファッション」「ビューティー」各1点ずつとシンプルにしたほうがいいのではという意見が出ています。いかがでしょうか？
```

**Comment by fumihumi** [comment]
うーん
> 審査員のみなさんが審査に集中したいのと、観客のみなさんにもステージに集中させたいため
これを考えるとスマホぽちぽちしながらステージ見るのはよくなさそうな雰囲気。

基本的な構成は `シンプル is Best` な投票にするしかないんですかねー

ファッションとビューティーでタブ分けして。それぞれ一番良いと思うものを選んでもらう。

もしくは
ファッションとビューティーから `1,2,3位`を選んでもらい
 {1: 10点, 2: 5点, 3: 3点}で係数つけて点数を累計して表示するか。
(→ファッションだけで１〜３になる可能性もある)

**Comment by fumihumi** [comment]
あとで別のISSUEにまとめます
