### ISSUE TITLE
webpack-server導入する

### ISSUE THREAD

**Issue by wh1tecat-nya** [ISC-MakeIT/f_college_sns#17]
## なにを実装したいのか
[webpack/webpack-dev-server](https://github.com/webpack/webpack-dev-server)
[webpack-contrib/webpack-serve](https://github.com/webpack-contrib/webpack-serve)
## なぜ実装したいのか
+ CORS等の対策のため、ローカルのindex.htmlを直にブラウザを開くことはやめたい。
+ また、HMRによるauto reloadに対応し、webpackがpackしたbundleファイルを自動で再読込してくれるため開発効率が上昇する。
## 実装することで'だれが'、'どんな風に'幸せになれるのか
+ 開発関係者全員
## 仕様
[webpack/webpack-dev-server](https://github.com/webpack/webpack-dev-server)は古く、[webpack-contrib/webpack-serve](https://github.com/webpack-contrib/webpack-serve)に今後は開発がシフトするようだが、現状まだ外部のドキュメント等が不足しているため、それぞれの可用性などについて調査する必要がある。
## 参考
[webpack/webpack-dev-server](https://github.com/webpack/webpack-dev-server)
[DevServer](https://webpack.js.org/configuration/dev-server/)
[webpack-contrib/webpack-serve](https://github.com/webpack-contrib/webpack-serve)
[webpack-serve試してみたメモ](http://hinoshita.hatenadiary.com/entry/2018/05/13/220754)
[webpackとwebpack-serveで静的なWeb環境を作る](https://qiita.com/ma2saka/items/eb4190a009da9649583c)

**Comment by fumihumi** [comment]
ほぉ。なるほど

**Comment by fumihumi** [comment]
これは結局Depli cationだったやつ
