### ISSUE TITLE
一覧画面のフロント実装（画像の表示周り）

### ISSUE THREAD

**Issue by fumihumi** [ISC-MakeIT/f_college_sns#20]
加藤さんのデザイン草案をもとに綱島くんにお任せしてる

**Comment by yamato3310** [comment]
加藤さんの草案を再現する自信がないのですが。画像の幅とかも自分で決めるかんじですか？

**Comment by fumihumi** [comment]
フィーリングで行こう。w

サイズ感は
一番大きいやつは `85vw` or `90vw`
横に二つ並べる場合は
```css
display: flex;
flex-derection: row;
justify-content: space-around;(こんな感じだった気がする)
width: 42vw;
```

三つ以上のやつは `30vw`とかで調整してみようか。
細かい調整は後々していくので一旦はざっくりのレイアウトを作ってみて！
そのあとpxレベルでの調整など必要ならやっていきます！

**Comment by yamato3310** [comment]
了解です。そこまで行くのにまだ数日はかかりますが

**Comment by fumihumi** [comment]
- 画像の出し分けするコンポーネントつくる
- それを元に表示する
- CSS頑張る **自力で**
