### ISSUE TITLE
APIのモックアップ作成

### ISSUE THREAD

**Issue by fumihumi** [ISC-MakeIT/f_college_sns#22]
山崎先輩に口頭でお願いしているけれどなんかまとめて置いた方が良い気がする。

とりあえず↓に書いていく予定。
https://app.swaggerhub.com/apis/fumihumi/f_college_sns_api/1.0.0#/

- [x] 必要なリソースの確定
- [x] 一覧系API
- [x] 詳細APi
- [ ] その他必要なものの検討
- [ ] いいねボタンとかつけると思うし。それの部分とか？

- [ ] 投票部分のAPIとか

**Comment by fumihumi** [comment]
書いた。なんか配列がうまく記入できなかった

https://app.swaggerhub.com/apis/fumihumi/f_college_sns_api/1.0.0#/

**Comment by ymzk-jp** [comment]
上記のドキュメントは[こちら](https://app.swaggerhub.com/apis/iot_semi/f-college_sns_api/1.0.0)に移動しました
https://app.swaggerhub.com/apis/iot_semi/f-college_sns_api/1.0.0

**Comment by ymzk-jp** [comment]
アカウントは共有とします。変更する際は該当iot-semiのアカウントでログインして編集してください。
アカウント情報はmake it のdriveにあります（discord #ファイル置き場 参照）
