### ISSUE TITLE
多量コンテンツの最適な表示UIについて検討および実装

### ISSUE THREAD

**Issue by fumihumi** [ISC-MakeIT/f_college_sns#29]
## なにを実装したいのか

単純なリスト表示だとなんか人間によくないんじゃないか説があった。

ので全力で暇をしている (暇とはいってない) @wh1tecat-nya にお任せする

なんかアイデアあるっぽいのでサクッとモックアップ作ってもらう予定。

------------

あとぼやきなんだけど、iphoneのホーム画面って 4 * 6 = 24 が数ページにある + ４つのアプリをfooter固定しているのを考えるとそういうのもありなのかもしれない。

**Comment by wh1tecat-nya** [comment]
今日・明日あたりでやる予定

**Comment by wh1tecat-nya** [comment]
~~一応まとめ
・今回のケースだと50件の表示がある
・全件に画像があり、画像も主要コンテンツの一つになる。
・結局の所、50件もあって全部~~

ここまで書いてたけどアイコン風UI超絶ありな気がしたのでcloseしたい感

**Comment by fumihumi** [comment]
クローズしますか
