### ISSUE TITLE
discordってcircle CI 連携できないのかな。

### ISSUE THREAD

**Issue by fumihumi** [ISC-MakeIT/f_college_sns#30]

**Comment by wh1tecat-nya** [comment]
お

**Comment by fumihumi** [comment]
CIのリアルタイムのpass|failした時の通知があるならって感じ

**Comment by wh1tecat-nya** [comment]
一応webhookがslack互換なので#github-logと同じような感じならいけそう

**Comment by wh1tecat-nya** [comment]
(公式)https://support.discordapp.com/hc/en-us/articles/228383668-Intro-to-Webhooks

**Comment by fumihumi** [comment]
ほぉ、slackやとリアルタイムで見えるんすよねぇ。thx

**Comment by wh1tecat-nya** [comment]
bot作るか・・・

**Comment by fumihumi** [comment]
まぁブラウザで通知くるからいらないといえばいらないんだけどあったら便利程度な

**Comment by fumihumi** [comment]
done
