### ISSUE TITLE
デプロイ方法検討だけしとく

### ISSUE THREAD

**Issue by fumihumi** [ISC-MakeIT/f_college_sns#31]
- AWS
    - [x] elastic beans talk 
        - python製のCLIコマンドでサクッとデプロイできるやつ
- heroku 
    - おなじみHEROKU
- GCP ?

**Comment by fumihumi** [comment]
お盆明けに作業するか。

**Comment by ymzk-jp** [comment]
これ全部使うの？？？
選択肢？
```
AWS
 elastic beans talk
python製のCLIコマンドでサクッとデプロイできるやつ
heroku
おなじみHEROKU
GCP ?
```

**Comment by fumihumi** [comment]
選択肢ですねー

安心と安全のAWS感はあるので特に理由がなければ（デプロイミスるとか）AWSな気はしますが

**Comment by fumihumi** [comment]
> https://github.com/ISC-MakeIT/f_college_api
こっちがホストになるっぽいしこのrepoでは検討しなそう
