### ISSUE TITLE
<<土下座案件>>  共有とお願い

### ISSUE THREAD

**Issue by fumihumi** [ISC-MakeIT/f_college_sns#32]
9末から10月にかけて某社さんのコンテストに参加したいなぁと思ってます。(下記に日程添付)

日曜から数日悩んだんですがそれでも行きたいなぁと。
- せっかくいただいたコンテストへの挑戦権を無駄にしたくない。
- 自己の成長につながるのではと考えた上で参加したいと言う気持ちが強いです
- それ以上に前回負けて悔しいので勝ちに行きたい

-------

クリティカルな問題として、本案件の **当日10/27** が **↑某コンテストの本番** ってことで
本案権に立ち会わせられないという状況になってしまいました。
いわゆる、ダブルブッキングな事案を引き起こしました。 **申し訳ないです。**

2点お願いしたく。
- 開発は死ぬ気で9末に終わらせる(10月は保守だけ)にしたい
- 当日は僕なしでトラブルに立ち向かう…
(当日に本番DB弄るとかがあるのであればそれらの作業をお願いしたく。)

開発に関しては仕様検討を早急に終え実装に入らないとなぁという気持ちです。
2点目は基本的にトラブらないようにテストする予定ではあるけれど、まぁ100%とは言えないので内部の仕組みなどは各々で各機能を把握するようにしてもらいたい…。

最後に。
**死ぬほど無責任な事になってしまい申し訳無いんですがこちら承諾いただけないでしょうか！！**
日曜に返答する予定なのでそれまでに `みんなの承諾` 頂きたいと思ってます…！

**Comment by wh1tecat-nya** [comment]
しゃーなし　そのかわりコンテスト優勝で焼き肉ですよね？(9万だっけ？)

**Comment by fumihumi** [comment]
賞金でるのかな、わからん....w

**Comment by ymzk-jp** [comment]
優勝したら焼肉奢ったるわ

**Comment by fumihumi** [comment]
そういえばこれ日程問題なかったので大丈夫そう。本番いけます。
（開発がちゃんとできない。。がんばる）
